name: Bug report 🐞
description: Report an issue with Flutter PencilKit
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you proceed:

        - Make sure to check whether there are similar issues in the repository

  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise and descriptive explanation of what the bug is. Include screenshots or a video if needed. Tell us what were you expecting to happen instead of what is happening now.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Snack or a link to a repository
      description: |
        Please provide a repository on GitHub under your username that reproduces the issue.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve.
        Issues without a reproduction are likely to stale.
      placeholder: Link to a GitHub repository
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: package version
      description: What version of pencil_kit are you using?
      placeholder: 0.0.1
    validations:
      required: true

  - type: textarea
    id: flutter-doctor
    attributes:
      label: Flutter Doctor Output
      description: The standard out of `flutter doctor` run
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ## Additonal information

        Providing as much information as possible greatly helps us with reproducting the issues.

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      description: What mode your application is running?
      options:
        - Debug mode
        - Release mode

  - type: dropdown
    id: emulator
    attributes:
      label: Device
      description: How are you running your application?
      options:
        - iOS simulator
        - iPad simulator
        - iOS Real device
        - iPad Readl device

  - type: input
    id: device-model
    attributes:
      label: Device model
      description: What device you are experiencing this problem on? Specify full device name along with the version of the operating system it's running.
      placeholder: ex. iPhone 13 Pro (Readl device)

  - type: dropdown
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: I searched for similar issues in the repository.
      options:
        - 'Yes'
    validations:
      required: true
