name: Analyze
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze_and_test:
    name: Flutter analyze
    strategy:
      matrix:
        flutter: ['stable']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor
      - run: flutter --version
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze
